package main

import (
	"bufio"
	"fmt"
	"log"
	"os"
)

func predict(s string) []string {
	classes := [][]string{
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "", ""},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "", ""},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "datīvs", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "datīvs", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "datīvs", ""},
		{"īpašības vārds", "vienskaitlis", "sieviešu dzimte", "", "", "", "pārākā pakāpe", "datīvs", "noteiktā galotne"},
		{"īpašības vārds", "vienskaitlis", "sieviešu dzimte", "", "", "", "pārākā pakāpe", "datīvs", "noteiktā galotne"},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "datīvs", ""},
		{"īpašības vārds", "vienskaitlis", "sieviešu dzimte", "", "", "", "pārākā pakāpe", "datīvs", "noteiktā galotne"},
		{"īpašības vārds", "vienskaitlis", "vīriešu dzimte", "", "", "", "pārākā pakāpe", "datīvs", "noteiktā galotne"},
		{"īpašības vārds", "vienskaitlis", "vīriešu dzimte", "", "", "", "pamata pakāpe", "datīvs", "noteiktā galotne"},
		{"īpašības vārds", "vienskaitlis", "vīriešu dzimte", "", "", "", "", "datīvs", "noteiktā galotne"},
		{"darbības vārds", "vienskaitlis", "", "", "", "", "", "datīvs", ""},
		{"darbības vārds", "daudzskaitlis", "", "tagadne", "1. persona", "nenoteiksme", "", "", ""},
		{"īpašības vārds", "vienskaitlis", "vīriešu dzimte", "", "", "", "pamata pakāpe", "datīvs", "noteiktā galotne"},
		{"īpašības vārds", "vienskaitlis", "vīriešu dzimte", "", "", "", "pārākā pakāpe", "datīvs", "noteiktā galotne"},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "datīvs", ""},
		{"īpašības vārds", "vienskaitlis", "vīriešu dzimte", "", "", "", "pārākā pakāpe", "datīvs", "noteiktā galotne"},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "datīvs", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "datīvs", ""},
		{"lokāms ciešamās kārtas Tagadnes divdabis", "vienskaitlis", "sieviešu dzimte", "", "", "", "pamata pakāpe", "datīvs", "noteiktā galotne"},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "datīvs", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "datīvs", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "datīvs", ""},
		{"lietvārds", "vienskaitlis", "vīriešu dzimte", "", "", "", "pamata pakāpe", "datīvs", "noteiktā galotne"},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "datīvs", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "nominatīvs", ""},
		{"īpašības vārds", "daudzskaitlis", "vīriešu dzimte", "", "", "", "", "nominatīvs", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "datīvs", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "vokatīvs", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "datīvs", ""},
		{"īpašības vārds", "daudzskaitlis", "vīriešu dzimte", "", "", "", "", "nominatīvs", "noteiktā galotne"},
		{"īpašības vārds", "daudzskaitlis", "vīriešu dzimte", "", "", "", "pamata pakāpe", "nominatīvs", "noteiktā galotne"},
		{"īpašības vārds", "vienskaitlis", "vīriešu dzimte", "", "", "", "pamata pakāpe", "ģenitīvs", "noteiktā galotne"},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "", ""},
		{"īpašības vārds", "vienskaitlis", "vīriešu dzimte", "", "", "", "pamata pakāpe", "ģenitīvs", "noteiktā galotne"},
		{"īpašības vārds", "daudzskaitlis", "vīriešu dzimte", "", "", "", "pamata pakāpe", "nominatīvs", "noteiktā galotne"},
		{"īpašības vārds", "daudzskaitlis", "vīriešu dzimte", "", "", "", "vispārākā pakāpe", "nominatīvs", "noteiktā galotne"},
		{"īpašības vārds", "daudzskaitlis", "vīriešu dzimte", "", "", "", "pamata pakāpe", "nominatīvs", "noteiktā galotne"},
		{"darbības vārds", "vienskaitlis", "", "", "", "", "", "nominatīvs", ""},
		{"darbības vārds", "vienskaitlis", "", "pagātne", "", "nenoteiksme", "", "", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "nominatīvs", ""},
		{"darbības vārds", "vienskaitlis", "", "pagātne", "3. persona", "nenoteiksme", "", "", ""},
		{"darbības vārds", "vienskaitlis", "", "pagātne", "3. persona", "nenoteiksme", "", "", ""},
		{"darbības vārds", "vienskaitlis", "", "pagātne", "2. persona", "nenoteiksme", "", "", ""},
		{"īpašības vārds", "vienskaitlis", "vīriešu dzimte", "", "", "", "pārākā pakāpe", "nominatīvs", "noteiktā galotne"},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "nominatīvs", ""},
		{"īpašības vārds", "vienskaitlis", "vīriešu dzimte", "", "", "", "pārākā pakāpe", "nominatīvs", "noteiktā galotne"},
		{"īpašības vārds", "vienskaitlis", "sieviešu dzimte", "", "", "", "pārākā pakāpe", "nominatīvs", "noteiktā galotne"},
		{"īpašības vārds", "daudzskaitlis", "vīriešu dzimte", "", "", "", "pārākā pakāpe", "nominatīvs", "noteiktā galotne"},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "nominatīvs", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "ģenitīvs", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "nominatīvs", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "ģenitīvs", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "ģenitīvs", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "ģenitīvs", ""},
		{"darbības vārds", "vienskaitlis", "", "", "", "", "", "", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "ģenitīvs", ""},
		{"darbības vārds", "vienskaitlis", "", "", "", "nenoteiksme", "", "", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "ģenitīvs", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "nominatīvs", ""},
		{"darbības vārds", "vienskaitlis", "", "", "", "nenoteiksme", "", "", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "nominatīvs", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "ģenitīvs", ""},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "nominatīvs", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "", ""},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "nominatīvs", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "", ""},
		{"darbības vārds", "vienskaitlis", "", "nākotne", "2. persona", "nenoteiksme", "", "", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "akuzatīvs", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "vokatīvs", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "akuzatīvs", ""},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "nominatīvs", ""},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "datīvs", ""},
		{"īpašības vārds", "daudzskaitlis", "", "", "", "", "", "datīvs", "noteiktā galotne"},
		{"īpašības vārds", "daudzskaitlis", "vīriešu dzimte", "", "", "", "pamata pakāpe", "datīvs", "noteiktā galotne"},
		{"īpašības vārds", "daudzskaitlis", "sieviešu dzimte", "", "", "", "pamata pakāpe", "datīvs", "noteiktā galotne"},
		{"īpašības vārds", "daudzskaitlis", "vīriešu dzimte", "", "", "", "pārākā pakāpe", "datīvs", "noteiktā galotne"},
		{"īpašības vārds", "daudzskaitlis", "vīriešu dzimte", "", "", "", "pārākā pakāpe", "datīvs", "noteiktā galotne"},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "datīvs", ""},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "datīvs", ""},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "datīvs", ""},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "datīvs", ""},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "datīvs", ""},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "datīvs", ""},
		{"darbības vārds", "daudzskaitlis", "", "pagātne", "1. persona", "nenoteiksme", "", "", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "vokatīvs", ""},
		{"darbības vārds", "daudzskaitlis", "", "pagātne", "1. persona", "nenoteiksme", "", "", ""},
		{"īpašības vārds", "daudzskaitlis", "sieviešu dzimte", "", "", "", "pārākā pakāpe", "datīvs", "noteiktā galotne"},
		{"īpašības vārds", "daudzskaitlis", "sieviešu dzimte", "", "", "", "pārākā pakāpe", "datīvs", "noteiktā galotne"},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "datīvs", ""},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "datīvs", ""},
		{"darbības vārds", "daudzskaitlis", "", "", "", "nenoteiksme", "", "", ""},
		{"darbības vārds", "daudzskaitlis", "", "", "", "nenoteiksme", "", "", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "datīvs", ""},
		{"darbības vārds", "daudzskaitlis", "", "", "", "nenoteiksme", "", "", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "datīvs", ""},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "datīvs", ""},
		{"īpašības vārds", "daudzskaitlis", "", "", "", "", "", "akuzatīvs", ""},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "", ""},
		{"darbības vārds", "daudzskaitlis", "", "nākotne", "2. persona", "nenoteiksme", "", "", ""},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "ģenitīvs", ""},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "ģenitīvs", ""},
		{"īpašības vārds", "daudzskaitlis", "sieviešu dzimte", "", "", "", "pamata pakāpe", "ģenitīvs", "noteiktā galotne"},
		{"darbības vārds", "daudzskaitlis", "", "nākotne", "2. persona", "nenoteiksme", "", "", ""},
		{"darbības vārds", "daudzskaitlis", "", "tagadne", "2. persona", "nenoteiksme", "", "", ""},
		{"darbības vārds", "daudzskaitlis", "", "", "", "nenoteiksme", "", "", ""},
		{"darbības vārds", "vienskaitlis", "", "tagadne", "2. persona", "nenoteiksme", "", "", ""},
		{"darbības vārds", "vienskaitlis", "", "nākotne", "2. persona", "nenoteiksme", "", "", ""},
		{"darbības vārds", "vienskaitlis", "", "pagātne", "2. persona", "nenoteiksme", "", "", ""},
		{"darbības vārds", "vienskaitlis", "", "pagātne", "2. persona", "nenoteiksme", "", "", ""},
		{"darbības vārds", "daudzskaitlis", "", "pagātne", "1. persona", "nenoteiksme", "", "", ""},
		{"darbības vārds", "vienskaitlis", "", "nākotne", "3. persona", "nenoteiksme", "", "", ""},
		{"darbības vārds", "daudzskaitlis", "", "tagadne", "2. persona", "nenoteiksme", "", "", ""},
		{"darbības vārds", "vienskaitlis", "", "tagadne", "2. persona", "nenoteiksme", "", "", ""},
		{"darbības vārds", "daudzskaitlis", "", "pagātne", "2. persona", "nenoteiksme", "", "", ""},
		{"darbības vārds", "vienskaitlis", "", "nākotne", "2. persona", "nenoteiksme", "", "", ""},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "ģenitīvs", ""},
		{"īpašības vārds", "daudzskaitlis", "sieviešu dzimte", "", "", "", "pārākā pakāpe", "ģenitīvs", "noteiktā galotne"},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "", ""},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "ģenitīvs", ""},
		{"darbības vārds", "daudzskaitlis", "", "", "", "nenoteiksme", "", "", ""},
		{"īpašības vārds", "daudzskaitlis", "sieviešu dzimte", "", "", "", "pārākā pakāpe", "akuzatīvs", "noteiktā galotne"},
		{"īpašības vārds", "daudzskaitlis", "sieviešu dzimte", "", "", "", "pamata pakāpe", "ģenitīvs", "noteiktā galotne"},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "ģenitīvs", ""},
		{"īpašības vārds", "daudzskaitlis", "sieviešu dzimte", "", "", "", "pamata pakāpe", "akuzatīvs", "noteiktā galotne"},
		{"īpašības vārds", "daudzskaitlis", "sieviešu dzimte", "", "", "", "pārākā pakāpe", "akuzatīvs", "noteiktā galotne"},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "ģenitīvs", ""},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "ģenitīvs", ""},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "ģenitīvs", ""},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "ģenitīvs", ""},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "pamata pakāpe", "ģenitīvs", "noteiktā galotne"},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "ģenitīvs", ""},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "ģenitīvs", ""},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "ģenitīvs", ""},
		{"lokāms darāmās kārtas Tagadnes divdabis", "daudzskaitlis", "sieviešu dzimte", "", "", "", "", "ģenitīvs", "noteiktā galotne"},
		{"īpašības vārds", "daudzskaitlis", "vīriešu dzimte", "", "", "", "", "akuzatīvs", "noteiktā galotne"},
		{"īpašības vārds", "vienskaitlis", "vīriešu dzimte", "", "", "", "pārākā pakāpe", "nominatīvs", "noteiktā galotne"},
		{"īpašības vārds", "vienskaitlis", "vīriešu dzimte", "", "", "", "vispārākā pakāpe", "ģenitīvs", "noteiktā galotne"},
		{"īpašības vārds", "vienskaitlis", "vīriešu dzimte", "", "", "", "pamata pakāpe", "ģenitīvs", "noteiktā galotne"},
		{"īpašības vārds", "vienskaitlis", "", "", "", "", "", "", ""},
		{"īpašības vārds", "vienskaitlis", "vīriešu dzimte", "", "", "", "pamata pakāpe", "ģenitīvs", "noteiktā galotne"},
		{"īpašības vārds", "vienskaitlis", "vīriešu dzimte", "", "", "", "vispārākā pakāpe", "ģenitīvs", "noteiktā galotne"},
		{"īpašības vārds", "vienskaitlis", "vīriešu dzimte", "", "", "", "vispārākā pakāpe", "ģenitīvs", "noteiktā galotne"},
		{"īpašības vārds", "vienskaitlis", "vīriešu dzimte", "", "", "", "pārākā pakāpe", "ģenitīvs", "noteiktā galotne"},
		{"lokāms ciešamās kārtas Tagadnes divdabis", "vienskaitlis", "vīriešu dzimte", "", "", "", "vispārākā pakāpe", "ģenitīvs", "noteiktā galotne"},
		{"īpašības vārds", "vienskaitlis", "vīriešu dzimte", "", "", "", "pārākā pakāpe", "akuzatīvs", "noteiktā galotne"},
		{"lokāms ciešamās kārtas Pagātnes divdabis", "vienskaitlis", "vīriešu dzimte", "", "", "", "vispārākā pakāpe", "ģenitīvs", "noteiktā galotne"},
		{"īpašības vārds", "vienskaitlis", "vīriešu dzimte", "", "", "", "pamata pakāpe", "ģenitīvs", "noteiktā galotne"},
		{"īpašības vārds", "vienskaitlis", "vīriešu dzimte", "", "", "", "", "nominatīvs", "noteiktā galotne"},
		{"īpašības vārds", "vienskaitlis", "vīriešu dzimte", "", "", "", "pamata pakāpe", "nominatīvs", "noteiktā galotne"},
		{"īpašības vārds", "vienskaitlis", "vīriešu dzimte", "", "", "", "pārākā pakāpe", "nominatīvs", "noteiktā galotne"},
		{"īpašības vārds", "vienskaitlis", "vīriešu dzimte", "", "", "", "pamata pakāpe", "nominatīvs", "noteiktā galotne"},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "nominatīvs", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "nominatīvs", ""},
		{"īpašības vārds", "vienskaitlis", "vīriešu dzimte", "", "", "", "pārākā pakāpe", "nominatīvs", "noteiktā galotne"},
		{"īpašības vārds", "daudzskaitlis", "", "", "", "", "", "lokatīvs", "noteiktā galotne"},
		{"īpašības vārds", "daudzskaitlis", "sieviešu dzimte", "", "", "", "pārākā pakāpe", "lokatīvs", "noteiktā galotne"},
		{"īpašības vārds", "daudzskaitlis", "vīriešu dzimte", "", "", "", "pārākā pakāpe", "lokatīvs", "noteiktā galotne"},
		{"īpašības vārds", "daudzskaitlis", "vīriešu dzimte", "", "", "", "pamata pakāpe", "lokatīvs", "noteiktā galotne"},
		{"īpašības vārds", "daudzskaitlis", "vīriešu dzimte", "", "", "", "pamata pakāpe", "lokatīvs", "noteiktā galotne"},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "akuzatīvs", ""},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "", ""},
		{"īpašības vārds", "daudzskaitlis", "vīriešu dzimte", "", "", "", "pamata pakāpe", "akuzatīvs", "noteiktā galotne"},
		{"īpašības vārds", "daudzskaitlis", "vīriešu dzimte", "", "", "", "pamata pakāpe", "akuzatīvs", "noteiktā galotne"},
		{"darbības vārds", "vienskaitlis", "", "pagātne", "1. persona", "nenoteiksme", "", "", ""},
		{"īpašības vārds", "daudzskaitlis", "vīriešu dzimte", "", "", "", "pārākā pakāpe", "akuzatīvs", "noteiktā galotne"},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "akuzatīvs", ""},
		{"īpašības vārds", "daudzskaitlis", "vīriešu dzimte", "", "", "", "pārākā pakāpe", "akuzatīvs", "noteiktā galotne"},
		{"īpašības vārds", "daudzskaitlis", "vīriešu dzimte", "", "", "", "pamata pakāpe", "akuzatīvs", "noteiktā galotne"},
		{"īpašības vārds", "daudzskaitlis", "vīriešu dzimte", "", "", "", "pārākā pakāpe", "akuzatīvs", "noteiktā galotne"},
		{"īpašības vārds", "daudzskaitlis", "sieviešu dzimte", "", "", "", "pārākā pakāpe", "lokatīvs", "noteiktā galotne"},
		{"darbības vārds", "daudzskaitlis", "", "", "", "nenoteiksme", "", "", ""},
		{"īpašības vārds", "daudzskaitlis", "sieviešu dzimte", "", "", "", "pārākā pakāpe", "lokatīvs", "noteiktā galotne"},
		{"īpašības vārds", "daudzskaitlis", "sieviešu dzimte", "", "", "", "pamata pakāpe", "lokatīvs", "noteiktā galotne"},
		{"īpašības vārds", "daudzskaitlis", "sieviešu dzimte", "", "", "", "pamata pakāpe", "lokatīvs", "noteiktā galotne"},
		{"īpašības vārds", "daudzskaitlis", "sieviešu dzimte", "", "", "", "pamata pakāpe", "", "noteiktā galotne"},
		{"īpašības vārds", "daudzskaitlis", "sieviešu dzimte", "", "", "", "pamata pakāpe", "lokatīvs", "noteiktā galotne"},
		{"darbības vārds", "daudzskaitlis", "", "pagātne", "3. persona", "nenoteiksme", "", "", ""},
		{"īpašības vārds", "daudzskaitlis", "sieviešu dzimte", "", "", "", "pārākā pakāpe", "akuzatīvs", "noteiktā galotne"},
		{"īpašības vārds", "daudzskaitlis", "sieviešu dzimte", "", "", "", "pamata pakāpe", "lokatīvs", "noteiktā galotne"},
		{"īpašības vārds", "daudzskaitlis", "sieviešu dzimte", "", "", "", "pārākā pakāpe", "akuzatīvs", "noteiktā galotne"},
		{"īpašības vārds", "daudzskaitlis", "sieviešu dzimte", "", "", "", "pārākā pakāpe", "akuzatīvs", "noteiktā galotne"},
		{"lokāms ciešamās kārtas Tagadnes divdabis", "daudzskaitlis", "sieviešu dzimte", "", "", "", "pārākā pakāpe", "vokatīvs", "noteiktā galotne"},
		{"īpašības vārds", "daudzskaitlis", "sieviešu dzimte", "", "", "", "pārākā pakāpe", "akuzatīvs", "noteiktā galotne"},
		{"lokāms ciešamās kārtas Pagātnes divdabis", "daudzskaitlis", "sieviešu dzimte", "", "", "", "pārākā pakāpe", "akuzatīvs", "noteiktā galotne"},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "lokatīvs", ""},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "", ""},
		{"darbības vārds", "daudzskaitlis", "", "", "", "", "", "", ""},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "lokatīvs", ""},
		{"darbības vārds", "daudzskaitlis", "", "", "", "nenoteiksme", "", "", ""},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "pamata pakāpe", "akuzatīvs", "noteiktā galotne"},
		{"lietvārds", "daudzskaitlis", "sieviešu dzimte", "", "", "", "pamata pakāpe", "akuzatīvs", "noteiktā galotne"},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "pamata pakāpe", "akuzatīvs", "noteiktā galotne"},
		{"lokāms ciešamās kārtas Pagātnes divdabis", "vienskaitlis", "vīriešu dzimte", "", "", "", "pamata pakāpe", "ģenitīvs", "noteiktā galotne"},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "akuzatīvs", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "nominatīvs", ""},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "akuzatīvs", ""},
		{"īpašības vārds", "daudzskaitlis", "sieviešu dzimte", "", "", "", "pamata pakāpe", "lokatīvs", "noteiktā galotne"},
		{"īpašības vārds", "daudzskaitlis", "sieviešu dzimte", "", "", "", "pamata pakāpe", "lokatīvs", "noteiktā galotne"},
		{"īpašības vārds", "daudzskaitlis", "sieviešu dzimte", "", "", "", "pamata pakāpe", "", "noteiktā galotne"},
		{"lokāms ciešamās kārtas Tagadnes divdabis", "daudzskaitlis", "sieviešu dzimte", "", "", "", "pamata pakāpe", "vokatīvs", "noteiktā galotne"},
		{"darbības vārds", "daudzskaitlis", "", "", "", "", "", "", ""},
		{"īpašības vārds", "daudzskaitlis", "sieviešu dzimte", "", "", "", "pamata pakāpe", "akuzatīvs", "noteiktā galotne"},
		{"darbības vārds", "daudzskaitlis", "", "", "", "nenoteiksme", "", "", ""},
		{"īpašības vārds", "daudzskaitlis", "sieviešu dzimte", "", "", "", "pamata pakāpe", "lokatīvs", "noteiktā galotne"},
		{"darbības vārds", "daudzskaitlis", "", "nākotne", "3. persona", "nenoteiksme", "", "", ""},
		{"īpašības vārds", "daudzskaitlis", "sieviešu dzimte", "", "", "", "pamata pakāpe", "lokatīvs", "noteiktā galotne"},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "lokatīvs", ""},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "lokatīvs", ""},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "lokatīvs", ""},
		{"darbības vārds", "daudzskaitlis", "", "nākotne", "3. persona", "nenoteiksme", "", "", ""},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "lokatīvs", ""},
		{"lokāms darāmās kārtas Tagadnes divdabis", "vienskaitlis", "vīriešu dzimte", "", "", "", "pamata pakāpe", "akuzatīvs", "noteiktā galotne"},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "lokatīvs", ""},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "lokatīvs", ""},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "lokatīvs", ""},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "akuzatīvs", ""},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "akuzatīvs", ""},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "lokatīvs", ""},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "akuzatīvs", ""},
		{"lokāms darāmās kārtas Pagātnes divdabis", "daudzskaitlis", "sieviešu dzimte", "", "", "", "", "akuzatīvs", "noteiktā galotne"},
		{"lokāms darāmās kārtas Tagadnes divdabis", "daudzskaitlis", "sieviešu dzimte", "", "", "", "pamata pakāpe", "akuzatīvs", "noteiktā galotne"},
		{"lokāms darāmās kārtas Pagātnes divdabis", "daudzskaitlis", "sieviešu dzimte", "", "", "", "", "akuzatīvs", "noteiktā galotne"},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "lokatīvs", ""},
		{"darbības vārds", "vienskaitlis", "", "nākotne", "1. persona", "nenoteiksme", "", "", ""},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "lokatīvs", ""},
		{"darbības vārds", "daudzskaitlis", "", "", "", "nenoteiksme", "", "", ""},
		{"darbības vārds", "daudzskaitlis", "", "tagadne", "2. persona", "nenoteiksme", "", "", ""},
		{"darbības vārds", "daudzskaitlis", "", "tagadne", "2. persona", "nenoteiksme", "", "", ""},
		{"darbības vārds", "daudzskaitlis", "", "tagadne", "2. persona", "nenoteiksme", "", "", ""},
		{"darbības vārds", "daudzskaitlis", "", "", "2. persona", "nenoteiksme", "", "", ""},
		{"darbības vārds", "daudzskaitlis", "", "tagadne", "2. persona", "nenoteiksme", "", "", ""},
		{"darbības vārds", "daudzskaitlis", "", "", "", "nenoteiksme", "", "", ""},
		{"darbības vārds", "daudzskaitlis", "", "", "", "nenoteiksme", "", "", ""},
		{"darbības vārds", "daudzskaitlis", "", "nākotne", "2. persona", "nenoteiksme", "", "", ""},
		{"darbības vārds", "daudzskaitlis", "", "tagadne", "2. persona", "nenoteiksme", "", "", ""},
		{"darbības vārds", "vienskaitlis", "", "tagadne", "3. persona", "nenoteiksme", "", "", ""},
		{"darbības vārds", "daudzskaitlis", "", "pagātne", "2. persona", "nenoteiksme", "", "", ""},
		{"darbības vārds", "daudzskaitlis", "", "nākotne", "2. persona", "nenoteiksme", "", "", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "vokatīvs", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "ģenitīvs", ""},
		{"īpašības vārds", "vienskaitlis", "", "", "", "", "", "akuzatīvs", "noteiktā galotne"},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "akuzatīvs", ""},
		{"darbības vārds", "vienskaitlis", "", "", "1. persona", "nenoteiksme", "", "", ""},
		{"īpašības vārds", "vienskaitlis", "", "", "", "", "pamata pakāpe", "akuzatīvs", "noteiktā galotne"},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "akuzatīvs", ""},
		{"īpašības vārds", "vienskaitlis", "sieviešu dzimte", "", "", "", "pamata pakāpe", "akuzatīvs", "noteiktā galotne"},
		{"īpašības vārds", "vienskaitlis", "sieviešu dzimte", "", "", "", "pamata pakāpe", "akuzatīvs", "noteiktā galotne"},
		{"darbības vārds", "vienskaitlis", "", "pagātne", "1. persona", "nenoteiksme", "", "", ""},
		{"īpašības vārds", "vienskaitlis", "vīriešu dzimte", "", "", "", "pārākā pakāpe", "akuzatīvs", "noteiktā galotne"},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "akuzatīvs", ""},
		{"īpašības vārds", "vienskaitlis", "", "", "", "", "pamata pakāpe", "akuzatīvs", "noteiktā galotne"},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "akuzatīvs", ""},
		{"lokāms ciešamās kārtas Tagadnes divdabis", "vienskaitlis", "vīriešu dzimte", "", "", "", "pamata pakāpe", "akuzatīvs", "noteiktā galotne"},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "akuzatīvs", ""},
		{"īpašības vārds", "vienskaitlis", "vīriešu dzimte", "", "", "", "pamata pakāpe", "akuzatīvs", "noteiktā galotne"},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "akuzatīvs", ""},
		{"īpašības vārds", "daudzskaitlis", "vīriešu dzimte", "", "", "", "pārākā pakāpe", "ģenitīvs", "noteiktā galotne"},
		{"īpašības vārds", "daudzskaitlis", "vīriešu dzimte", "", "", "", "pārākā pakāpe", "ģenitīvs", "noteiktā galotne"},
		{"īpašības vārds", "vienskaitlis", "sieviešu dzimte", "", "", "", "pamata pakāpe", "ģenitīvs", "noteiktā galotne"},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "akuzatīvs", ""},
		{"īpašības vārds", "vienskaitlis", "sieviešu dzimte", "", "", "", "pamata pakāpe", "ģenitīvs", "noteiktā galotne"},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "akuzatīvs", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "akuzatīvs", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "akuzatīvs", ""},
		{"darbības vārds", "vienskaitlis", "", "", "", "nenoteiksme", "", "", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "akuzatīvs", ""},
		{"darbības vārds", "daudzskaitlis", "", "", "", "nenoteiksme", "", "", ""},
		{"darbības vārds", "vienskaitlis", "", "", "", "nenoteiksme", "", "", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "akuzatīvs", ""},
		{"darbības vārds", "vienskaitlis", "", "", "1. persona", "nenoteiksme", "", "", ""},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "ģenitīvs", ""},
		{"darbības vārds", "vienskaitlis", "", "", "", "", "", "", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "ģenitīvs", ""},
		{"darbības vārds", "vienskaitlis", "", "nākotne", "1. persona", "nenoteiksme", "", "", ""},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "ģenitīvs", ""},
		{"īpašības vārds", "vienskaitlis", "vīriešu dzimte", "", "", "", "pamata pakāpe", "akuzatīvs", "noteiktā galotne"},
		{"lietvārds", "daudzskaitlis", "", "", "", "", "", "ģenitīvs", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "lokatīvs", ""},
		{"īpašības vārds", "vienskaitlis", "sieviešu dzimte", "", "", "", "", "lokatīvs", "noteiktā galotne"},
		{"īpašības vārds", "vienskaitlis", "sieviešu dzimte", "", "", "", "pārākā pakāpe", "lokatīvs", "noteiktā galotne"},
		{"īpašības vārds", "vienskaitlis", "sieviešu dzimte", "", "", "", "pamata pakāpe", "lokatīvs", "noteiktā galotne"},
		{"īpašības vārds", "vienskaitlis", "vīriešu dzimte", "", "", "", "pamata pakāpe", "lokatīvs", "noteiktā galotne"},
		{"īpašības vārds", "vienskaitlis", "vīriešu dzimte", "", "", "", "vispārākā pakāpe", "lokatīvs", "noteiktā galotne"},
		{"īpašības vārds", "vienskaitlis", "vīriešu dzimte", "", "", "", "pamata pakāpe", "lokatīvs", "noteiktā galotne"},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "lokatīvs", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "lokatīvs", ""},
		{"īpašības vārds", "vienskaitlis", "sieviešu dzimte", "", "", "", "pamata pakāpe", "lokatīvs", "noteiktā galotne"},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "lokatīvs", ""},
		{"īpašības vārds", "vienskaitlis", "sieviešu dzimte", "", "", "", "pamata pakāpe", "lokatīvs", "noteiktā galotne"},
		{"īpašības vārds", "vienskaitlis", "sieviešu dzimte", "", "", "", "pārākā pakāpe", "lokatīvs", "noteiktā galotne"},
		{"īpašības vārds", "vienskaitlis", "sieviešu dzimte", "", "", "", "pamata pakāpe", "lokatīvs", "noteiktā galotne"},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "lokatīvs", ""},
		{"īpašības vārds", "vienskaitlis", "sieviešu dzimte", "", "", "", "pamata pakāpe", "lokatīvs", "noteiktā galotne"},
		{"īpašības vārds", "vienskaitlis", "sieviešu dzimte", "", "", "", "pārākā pakāpe", "lokatīvs", "noteiktā galotne"},
		{"īpašības vārds", "vienskaitlis", "sieviešu dzimte", "", "", "", "pārākā pakāpe", "lokatīvs", "noteiktā galotne"},
		{"lokāms ciešamās kārtas Pagātnes divdabis", "vienskaitlis", "sieviešu dzimte", "", "", "", "pārākā pakāpe", "ģenitīvs", "noteiktā galotne"},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "lokatīvs", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "lokatīvs", ""},
		{"lokāms ciešamās kārtas Tagadnes divdabis", "vienskaitlis", "sieviešu dzimte", "", "", "", "pamata pakāpe", "lokatīvs", "noteiktā galotne"},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "lokatīvs", ""},
		{"īpašības vārds", "vienskaitlis", "sieviešu dzimte", "", "", "", "pamata pakāpe", "lokatīvs", "noteiktā galotne"},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "lokatīvs", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "pamata pakāpe", "lokatīvs", "noteiktā galotne"},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "lokatīvs", ""},
		{"lokāms ciešamās kārtas Pagātnes divdabis", "vienskaitlis", "sieviešu dzimte", "", "", "", "pamata pakāpe", "lokatīvs", "noteiktā galotne"},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "vokatīvs", ""},
		{"darbības vārds", "vienskaitlis", "", "", "", "nenoteiksme", "", "", ""},
		{"darbības vārds", "vienskaitlis", "", "", "", "nenoteiksme", "", "", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "lokatīvs", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "vokatīvs", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "vokatīvs", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "nominatīvs", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "lokatīvs", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "lokatīvs", ""},
		{"darbības vārds", "vienskaitlis", "", "", "", "nenoteiksme", "", "", ""},
		{"lietvārds", "vienskaitlis", "", "", "", "", "", "nominatīvs", ""},
	}
	feature := []int{7, 7, 7, 6, 5, 7, 5, -2, -2, 4, -2, 5, 4, -2, -2, 4, -2, -2, 4, 5, -2, -2, 5, -2, -2, 7, 6, 6, 6, -2, -2, 6, 7, 5, -2, -2, 5, -2, -2, 6, 5, -2, 7, -2, -2, 5, -2, 7, -2, -2, 7, 6, 7, 7, 4, 5, 5, -2, -2, -2, -2, -2, -2, -2, 6, 6, -2, 6, -2, 5, -2, -2, -2, 5, 4, 4, -2, 6, -2, -2, 5, 5, 4, -2, -2, 6, -2, -2, 5, -2, -2, 6, 5, 5, -2, -2, -2, -2, 6, 5, 5, 5, -2, -2, 2, 3, -2, 4, 4, 4, -2, -2, -2, 3, -2, -2, -2, 5, 5, 4, -2, -2, 4, 4, -2, -2, -2, 5, 5, 6, 3, -2, -2, -2, -2, -2, 6, 7, 5, 0, -2, -2, 5, 4, 3, -2, -2, -2, -2, 5, 4, -2, -2, 5, -2, -2, 5, 6, 5, 4, -2, 4, -2, 5, -2, -2, 4, -2, 4, -2, -2, 5, -2, 5, 4, -2, 5, -2, -2, 4, -2, 3, 2, -2, -2, -2, 5, 6, 5, -2, -2, 6, 6, 7, -2, 6, -2, -2, 3, 4, 5, -2, 3, -2, 4, -2, -2, -2, -2, 6, 4, -2, -2, -2, 5, 6, -2, 6, -2, -2, 4, 4, -2, -2, 4, -2, -2, 7, 6, 5, 6, 6, -2, 4, -2, -2, 6, -2, -2, -2, -2, 6, 6, 5, 5, -2, -2, 6, -2, 6, -2, -2, 5, 5, 5, 5, -2, -2, -2, -2, 6, -2, -2, 5, 4, -2, 6, 5, -2, -2, -2, 6, 6, -2, -2, 5, 5, -2, -2, 6, -2, -2, 7, 6, 6, 5, 4, -2, -2, 5, -2, 6, -2, -2, 5, 5, -2, -2, 4, -2, -2, 5, 6, -2, 4, -2, -2, 6, -2, -2, 7, 5, -2, -2, 6, -2, 6, 7, -2, -2, -2}
	threshold := []float32{189.5, 115.5, 110.5, 97.5, 108.5, 106.5, 101.0, -2.0, -2.0, 97.5, -2.0, 106.5, 287.0, -2.0, -2.0, 114.5, -2.0, -2.0, 106.0, 109.5, -2.0, -2.0, 115.5, -2.0, -2.0, 108.5, 107.5, 102.5, 100.5, -2.0, -2.0, 105.5, 100.5, 287.0, -2.0, -2.0, 107.5, -2.0, -2.0, 106.5, 110.0, -2.0, 99.0, -2.0, -2.0, 114.5, -2.0, 101.0, -2.0, -2.0, 102.5, 305.0, 100.5, 97.5, 339.5, 106.0, 104.5, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, 313.5, 114.5, -2.0, 115.5, -2.0, 287.0, -2.0, -2.0, -2.0, 109.5, 107.5, 97.5, -2.0, 103.0, -2.0, -2.0, 106.5, 105.5, 305.0, -2.0, -2.0, 187.0, -2.0, -2.0, 107.5, -2.0, -2.0, 115.5, 115.5, 114.5, -2.0, -2.0, -2.0, -2.0, 102.5, 105.5, 104.5, 102.5, -2.0, -2.0, 339.5, 106.0, -2.0, 115.5, 114.5, 108.5, -2.0, -2.0, -2.0, 116.0, -2.0, -2.0, -2.0, 107.5, 106.5, 108.5, -2.0, -2.0, 189.5, 114.5, -2.0, -2.0, -2.0, 339.5, 321.0, 100.5, 339.5, -2.0, -2.0, -2.0, -2.0, -2.0, 110.5, 111.5, 189.5, 90.0, -2.0, -2.0, 266.0, 115.5, 97.5, -2.0, -2.0, -2.0, -2.0, 97.5, 107.5, -2.0, -2.0, 189.5, -2.0, -2.0, 107.5, 120.0, 106.5, 97.5, -2.0, 287.0, -2.0, 104.0, -2.0, -2.0, 114.5, -2.0, 119.5, -2.0, -2.0, 102.5, -2.0, 106.5, 97.5, -2.0, 103.5, -2.0, -2.0, 119.5, -2.0, 115.5, 97.5, -2.0, -2.0, -2.0, 305.0, 113.0, 115.5, -2.0, -2.0, 263.0, 189.5, 111.5, -2.0, 116.5, -2.0, -2.0, 339.5, 106.0, 109.5, -2.0, 97.5, -2.0, 104.0, -2.0, -2.0, -2.0, -2.0, 339.5, 287.0, -2.0, -2.0, -2.0, 339.5, 114.0, -2.0, 187.0, -2.0, -2.0, 119.5, 116.5, -2.0, -2.0, 287.0, -2.0, -2.0, 116.5, 266.0, 334.5, 110.5, 99.0, -2.0, 110.5, -2.0, -2.0, 187.0, -2.0, -2.0, -2.0, -2.0, 109.5, 106.5, 287.0, 110.5, -2.0, -2.0, 102.5, -2.0, 104.5, -2.0, -2.0, 189.5, 115.5, 114.5, 99.5, -2.0, -2.0, -2.0, -2.0, 107.5, -2.0, -2.0, 105.5, 97.5, -2.0, 263.0, 97.5, -2.0, -2.0, -2.0, 117.5, 115.5, -2.0, -2.0, 287.0, 189.5, -2.0, -2.0, 120.0, -2.0, -2.0, 263.0, 108.5, 106.5, 99.5, 107.5, -2.0, -2.0, 266.0, -2.0, 101.5, -2.0, -2.0, 187.0, 114.5, -2.0, -2.0, 115.5, -2.0, -2.0, 106.0, 109.5, -2.0, 97.5, -2.0, -2.0, 115.5, -2.0, -2.0, 287.0, 295.0, -2.0, -2.0, 105.5, -2.0, 313.5, 307.5, -2.0, -2.0, -2.0}
	left := []int{1, 2, 3, 4, 5, 6, 7, -1, -1, 10, -1, 12, 13, -1, -1, 16, -1, -1, 19, 20, -1, -1, 23, -1, -1, 26, 27, 28, 29, -1, -1, 32, 33, 34, -1, -1, 37, -1, -1, 40, 41, -1, 43, -1, -1, 46, -1, 48, -1, -1, 51, 52, 53, 54, 55, 56, 57, -1, -1, -1, -1, -1, -1, -1, 65, 66, -1, 68, -1, 70, -1, -1, -1, 74, 75, 76, -1, 78, -1, -1, 81, 82, 83, -1, -1, 86, -1, -1, 89, -1, -1, 92, 93, 94, -1, -1, -1, -1, 99, 100, 101, 102, -1, -1, 105, 106, -1, 108, 109, 110, -1, -1, -1, 114, -1, -1, -1, 118, 119, 120, -1, -1, 123, 124, -1, -1, -1, 128, 129, 130, 131, -1, -1, -1, -1, -1, 137, 138, 139, 140, -1, -1, 143, 144, 145, -1, -1, -1, -1, 150, 151, -1, -1, 154, -1, -1, 157, 158, 159, 160, -1, 162, -1, 164, -1, -1, 167, -1, 169, -1, -1, 172, -1, 174, 175, -1, 177, -1, -1, 180, -1, 182, 183, -1, -1, -1, 187, 188, 189, -1, -1, 192, 193, 194, -1, 196, -1, -1, 199, 200, 201, -1, 203, -1, 205, -1, -1, -1, -1, 210, 211, -1, -1, -1, 215, 216, -1, 218, -1, -1, 221, 222, -1, -1, 225, -1, -1, 228, 229, 230, 231, 232, -1, 234, -1, -1, 237, -1, -1, -1, -1, 242, 243, 244, 245, -1, -1, 248, -1, 250, -1, -1, 253, 254, 255, 256, -1, -1, -1, -1, 261, -1, -1, 264, 265, -1, 267, 268, -1, -1, -1, 272, 273, -1, -1, 276, 277, -1, -1, 280, -1, -1, 283, 284, 285, 286, 287, -1, -1, 290, -1, 292, -1, -1, 295, 296, -1, -1, 299, -1, -1, 302, 303, -1, 305, -1, -1, 308, -1, -1, 311, 312, -1, -1, 315, -1, 317, 318, -1, -1, -1}
	right := []int{282, 227, 98, 25, 18, 9, 8, -1, -1, 11, -1, 15, 14, -1, -1, 17, -1, -1, 22, 21, -1, -1, 24, -1, -1, 73, 50, 31, 30, -1, -1, 39, 36, 35, -1, -1, 38, -1, -1, 45, 42, -1, 44, -1, -1, 47, -1, 49, -1, -1, 64, 63, 62, 61, 60, 59, 58, -1, -1, -1, -1, -1, -1, -1, 72, 67, -1, 69, -1, 71, -1, -1, -1, 91, 80, 77, -1, 79, -1, -1, 88, 85, 84, -1, -1, 87, -1, -1, 90, -1, -1, 97, 96, 95, -1, -1, -1, -1, 136, 117, 104, 103, -1, -1, 116, 107, -1, 113, 112, 111, -1, -1, -1, 115, -1, -1, -1, 127, 122, 121, -1, -1, 126, 125, -1, -1, -1, 135, 134, 133, 132, -1, -1, -1, -1, -1, 156, 149, 142, 141, -1, -1, 148, 147, 146, -1, -1, -1, -1, 153, 152, -1, -1, 155, -1, -1, 186, 171, 166, 161, -1, 163, -1, 165, -1, -1, 168, -1, 170, -1, -1, 173, -1, 179, 176, -1, 178, -1, -1, 181, -1, 185, 184, -1, -1, -1, 214, 191, 190, -1, -1, 209, 198, 195, -1, 197, -1, -1, 208, 207, 202, -1, 204, -1, 206, -1, -1, -1, -1, 213, 212, -1, -1, -1, 220, 217, -1, 219, -1, -1, 224, 223, -1, -1, 226, -1, -1, 241, 240, 239, 236, 233, -1, 235, -1, -1, 238, -1, -1, -1, -1, 263, 252, 247, 246, -1, -1, 249, -1, 251, -1, -1, 260, 259, 258, 257, -1, -1, -1, -1, 262, -1, -1, 271, 266, -1, 270, 269, -1, -1, -1, 275, 274, -1, -1, 279, 278, -1, -1, 281, -1, -1, 310, 301, 294, 289, 288, -1, -1, 291, -1, 293, -1, -1, 298, 297, -1, -1, 300, -1, -1, 307, 304, -1, 306, -1, -1, 309, -1, -1, 314, 313, -1, -1, 316, -1, 320, 319, -1, -1, -1}

	var helper func(node int) []string
	helper = func(node int) []string {
		if left[node] >= 0 {
			if float32(int(s[feature[node]])) <= threshold[node] {
				return helper(left[node])
			} else {
				return helper(right[node])
			}
		} else {
			return classes[node]
		}
	}
	return helper(0)
}

func main() {
	scanner := bufio.NewScanner(os.Stdin)
	for scanner.Scan() {
		fmt.Println(predict(fmt.Sprintf("%9v", scanner.Text())))
	}

	if err := scanner.Err(); err != nil {
		log.Println(err)
	}
}
